server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # คืนค่า index.html เสมอ เพื่อให้ React Router ทำงานต่อได้
        try_files $uri $uri/ /index.html; 
    }
}